name: Scheduled Workflow

on:
  schedule:
    # Run at 1:23 AM UTC every day
    - cron: '23 1 * * *'
  workflow_dispatch: # Allow manual triggering for testing

concurrency:
  group: update-providers
  cancel-in-progress: false

jobs:
  # We want these jobs to run sequentially to ensure data integrity between commits
  update-asn-data:
    name: Update ASN Data
    uses: ./.github/workflows/update-ip2asn-data.yml

  process-asn-data:
    name: Process ASN Data
    needs: update-asn-data
    uses: ./.github/workflows/process-ip2asn-data.yml

  update-provider-lists:
    name: Update Provider Lists
    needs: process-asn-data
    uses: ./.github/workflows/update-provider-lists.yml
